lib/template/typescript_source.rb
packages/typescript/README.md
packages/typescript/package-lock.json
packages/typescript/package.json
packages/typescript/src/generated.ts

Making the `url` package an optional dependency. The React Native SDK will need this package and currently has it as a dependency, but the Web SDK won't and we shouldn't install or import it. This allows us to keep both SDKs happy.

Removing dependencies from typescript package

---

lib/template/typescript_source.rb
packages/typescript/src/generated.ts

Doing this so we can introduce a new "dispatchXPostMessageEvent" function that will rely on the same underlying internal message dispatching logic but use different parsing/validation logic.

Splitting message dispatch logic

---

.github/workflows/build-typescript-package.yml
packages/typescript/package-lock.json
packages/typescript/package.json
packages/typescript/src/lib.ts
packages/typescript/test/post_message_dispatch_test.ts

Adds an `npm run format` command that formats all files that need to be formatted, also updates CI to check that formatting was done.

Formatting Typescript with prettier

---

lib/post_message_definition.yml
packages/typescript/docs/generated.md

As per our conversation from last week, I'm adding a warning to the documentation for `mx/connect/stepChange`. It mentions that it for analytics purposes and not controlling user experience.

Adding warning to mx/connect/stepChange

---

lib/post_message_definition.rb
lib/post_message_definition.yml
lib/template/typescript_documentation.rb
lib/template/typescript_source.rb
packages/typescript/docs/react-native-sdk-generated.md
packages/typescript/docs/web-sdk-generated.md
packages/typescript/src/generated.ts
packages/typescript/src/lib.ts
packages/typescript/test/post_message_dispatch_test.ts

Adding support for optional fields and declares an optional `member_guid` field in the `mx/connect/oauthError` post message. Depends on https://github.com/mxenabled/widget-post-message-definitions/pull/13.

Optional fields + adding oauthError member_guid field

---

lib/post_message_definition.rb
lib/template/typescript_documentation.rb

Adding `documented: false` to a post message will prevent it from being included in the generated documentation.
Example:
```yaml
post_messages:
widget:
connect:
institutionSearch:
documented: false
payload:
<<: *user_session_properties
query: string
```

Post Message documented property

---

.github/workflows/build-ruby-generator.yml
.github/workflows/build-typescript-package.yml

Updating builds so that they trigger only after a pull request is created _and_ after every single push to the master branch. Cron schedules are unaffected by this change.

Standardizing build triggers

---

Gemfile
Gemfile.lock

Psych is a core library of Ruby so it's not necessary to define it in the project's dependency list, but I'm adding it as a way to prevent version mismatch. This fixes an issue that Sam was running into.

Pinning Psych version

---

lib/post_message_definition.yml
packages/typescript/src/generated.ts

The SDK listens for this from a client so it can communicates success
and errors to the connect widget.

Add oauthComplete post message definition.

---

lib/core_refinements/string_refinement.rb
lib/post_message_definition.rb
lib/template/swift_source.rb
packages/swift/Sources/Generated.swift

Generating the structs used to represent the post message payloads. No post message parsing or dispatching in this PR, that'll come in a separate PR.

Generating Swift payload structs

---

lib/template/base.rb
packages/typescript/src/generated.ts

We were including post message definitions under the [`client` group](https://github.com/mxenabled/widget-post-message-definitions/blob/66bfb1b2987cbe1b47b2debec11fb5c071d2096c/lib/post_message_definition.yml) (which currently only includes one definition, `mx/client/oathComplete`) when generating widget-specific code. This isn't right, since client post messages are not specific to a widget. I found this issue when working on the Swift generator, which is where it was causing issues. Checking the updated TypeScript code, and from what I can tell, this won't cause problems in the SDKs that use that code.

Excluding client post messages

---

lib/template/swift_source.rb
packages/swift/Sources/Generated.swift

These are the interfaces used by the SDK users that want to implement post message handlers and the internal dispatchers in the SDK.
You may notice I'm not generating entity handlers yet ([here](https://github.com/mxenabled/widget-post-message-definitions/pull/30/files#diff-bdbc7ecbf81398e3219d1219993057e73f2829fa40571c1d7299132a0e3fa42cR50-R54
) and [here](https://github.com/mxenabled/widget-post-message-definitions/pull/30/files#diff-bdbc7ecbf81398e3219d1219993057e73f2829fa40571c1d7299132a0e3fa42cR62-R66)), that's because those definitions are not complete. I'd like to add those fully, then introduce these.

Generating Swift event delegate protocols and extensions

---

lib/template/base.rb
lib/template/swift_source.rb
packages/swift/Sources/Generated.swift

You'll notice there's an empty `dispatch` method, I had to add this so that so the `Dispatcher` protocol was being met and I could properly test this code. I kept it since that's what I'll work on next.

Decoding post message metadata

---

lib/post_message_definition.rb
lib/template/swift_source.rb
packages/swift/Sources/Generated.swift

- Overloading the `==` operator in generated structs so that we can easily compare dispatched and received payloads in tests.
- Removing `NSObjectProtocol` inheritance from base delegate protocol to fix a mocking issue. We don't need our delegate protocols to inherit `NSObjectProtocol` in the first place.
- Removing name of unused parameter. Not necessary but makes the code more consistent.

Prepping Swift code for unit tests

---

.github/workflows/build-swift-package.yml
packages/swift/.gitignore
packages/swift/Package.resolved
packages/swift/Package.swift
packages/swift/Tests/DispatchingEventsToDelegateTests.swift

Installing dependencies required for running unit tests and updating CI to run the Swift tests. In addition, I'm adding a test target to the project (so we can build), an empty test class (so there's something to build/run), and caching the build output in the CI to speed things up.
The two dependencies I'm bringing in are [Quick](https://github.com/Quick/Quick) and [Mockingbird](https://github.com/birdrides/mockingbird). Quick is the test framework (which is a little nicer than the default XCTest) and Mockingbird is a mocking library that I use to mock the delegates in the tests. Mockingbird generates code, I'll add that in a future PR.
**Edit**: showing that the caching is working: [this is the build](https://github.com/mxenabled/widget-post-message-definitions/runs/7772021242) we ran …

Running Swift unit tests in CI

---

packages/swift/Tests/DispatchingEventsToDelegateTests.swift

Filling in the `DispatchingEventsToDelegateTests` test class with dispatching/parsing/delegate checks. I think I have the happy path covered. I'll add tests for error dispatching once that's implemented.

Dispatching events to delegate tests

---

packages/swift/Tests/DispatchingEventsToDelegateTests.swift
packages/swift/Tests/Generated/Mocks.swift

Testing the Pulse event dispatcher as a way to check that events with complex paths (like `overdraftWarning/cta/transferFunds`) are dispatched correctly. Had to re-generate the mocks since there's a new class being mocked.

Pulse dispatcher tests

---

lib/template/swift_source.rb
packages/swift/Sources/Generated.swift
packages/swift/Tests/DispatchingEventsToDelegateTests.swift
packages/swift/Tests/Generated/Mocks.swift

The generic event handler should take a `URL` instead of an `Event`. We may not always be able to generate an `Event`, but we _always_ want to call the generic handler. So we need to change this to the raw-most value that we know we'll always have, and that's the URL itself in the case of the iOS/Swift code.
This is the pattern we follow in other implementations where the original value is either a [string URL](https://github.com/mxenabled/widget-post-message-definitions/blob/60ff61b6e10742a32ec3d7b76005cf19c378b9de/packages/typescript/src/generated.ts#L634) or a [post message object](https://github.com/mxenabled/widget-post-message-definitions/blob/60ff61b6e10742a32ec3d7b76005cf19c378b9de/packages/typescript/src/generated.ts#L649).

Swift: generic event handler signature update

---

lib/template/swift_source.rb
packages/swift/Sources/Generated.swift
packages/swift/Tests/DispatchingEventsToDelegateTests.swift
packages/swift/Tests/Generated/Mocks.swift

Calling `widgetEvent(_ error: EventError)` when we can't parse an event URL.

Swift: error handler

---

packages/swift/Tests/DispatchingEventsToDelegateTests.swift

Grouping connect tests in their own describe block, and using `describe` instead of `context` where appropriate.

Swift: organizing tests

---

packages/swift/Package.swift

This isn't necessary at the moment but good to specify anyway, specially if we end up importing this package via SPM.

Swift: adding library output to SPM configuration

---

lib/template/swift_source.rb
packages/swift/Sources/Generated.swift

This returned value will be used in the iOS SDK to handle OAuth events.

Swift: Dispatcher.dispatch returns an optional Event

---

lib/post_message_definition.yml
packages/swift/Sources/Generated.swift
packages/typescript/docs/react-native-sdk-generated.md
packages/typescript/docs/web-sdk-generated.md
packages/typescript/package-lock.json
packages/typescript/package.json
packages/typescript/src/generated.ts

This PR adds the support of a new Connect postmessage: `backToSearch` with `context` as payload.
**Changes**
-  I updated `lib/post_message_definition.yml` to add new `backToSearch`  postmessage.
-  I run `./bin/run` to execute all generators
**Testing instructions** 
-  Checkout this branch and run `npm run build` in `widget-post-message-definitions/packages/typescript` folder
-  Update web-widget-sdk [package.json file](https://github.com/mxenabled/web-widget-sdk/blob/master/package.json#L61) to point to a local `widget-post-message-definitions` package, like so: `"@mxenabled/widget-post-message-definitions": "file:../widget-post-message-definitions/packages/typescript"` and run `npm install && npm ci && npm run build`.
- Update serenity [package.json …

Add backToSearch postmessage support
